### ISSUE TITLE
Start from the past?

### ISSUE THREAD

**Issue by isaac-manubag** [eyas-ranjous/timer-node#16]
does this have a feature to start from a specific period of time from the past? I was thinking I could use this for time tracking for tickets for our in house project management tool, and we need to load the timer for a ticket from when the user started it if whenever he closed the browser

**Comment by eyas-ranjous** [comment]
Hi @isaac-manubag 

Thanks for your feedback. Right now it starts from the moment you call the timer.start(). but it's something I can add for sure! Which would be an additional param for start like `.start(timestamp)` when provided it can calculate time from the past timestamp (ms since Jan 1, 1970) to now timestamp then add that to the current running time. Can you confirm that this is your use case?

**Comment by eyas-ranjous** [comment]
Hi @isaac-manubag 

I have released a new major version of the timer. please check it out

https://github.com/eyas-ranjous/timer-node

It now accepts starting the timer from a past timestamp, as well allowing to serialize the timer in its current state.
